server:
  port: 8082

management:
  security:
    enabled: false

spring:
  h2:
    console:
      enabled: true
  application:
    name: user-service



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5
